---
- name: Demonstrate Ansible fact gathering
  hosts: all
  gather_facts: true

  tasks:
    - name: Display all facts
      ansible.builtin.debug:
        var: ansible_facts  # this is the root for all gathered facts from "gather_facts: true"

    - name: Display operating system information
      ansible.builtin.debug:
        msg:
          # ansible has two methods for accessing a variable within ansible_facts
          - "Hostname: {{ ansible_hostname }}"     # use ansible_ as an entry or ansible_facts.
          - "Hostname (alt pattern): {{ ansible_facts.hostname }}"
          - ""
          - "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "OS (alt pattern): {{ ansible_facts.distribution }} {{ ansible_facts.distribution_version}}"
          - ""
          - "Kernel: {{ ansible_kernel }}"
          - "Kernel (alt pattern): {{ ansible_facts.kernel }}"
          - ""
          - "Architecture: {{ ansible_architecture }}"
          - "Architecture (alt.pattern): {{ ansible_facts.architecture }}"
